// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIzWJ85zaCTlASxuDoIGp_a9c8EnxFqEY',
    appId: '1:768002894558:web:811a4ed22d149ff574b04f',
    messagingSenderId: '768002894558',
    projectId: 'tcu-tie',
    authDomain: 'tcu-tie.firebaseapp.com',
    storageBucket: 'tcu-tie.appspot.com',
    measurementId: 'G-PJ80EJZZMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ7AMXT3rWEcFwXBBW8WSjW46aAevqcR8',
    appId: '1:768002894558:android:44291d904044679f74b04f',
    messagingSenderId: '768002894558',
    projectId: 'tcu-tie',
    storageBucket: 'tcu-tie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzE4ppUVzg3piCS_U6uCHfuKntfUX1qPE',
    appId: '1:768002894558:ios:f3f7166b3a7c1a0e74b04f',
    messagingSenderId: '768002894558',
    projectId: 'tcu-tie',
    storageBucket: 'tcu-tie.appspot.com',
    iosClientId: '768002894558-cn6rn5lb3i035srdudgl1q2g1joret0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeiteasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzE4ppUVzg3piCS_U6uCHfuKntfUX1qPE',
    appId: '1:768002894558:ios:f3f7166b3a7c1a0e74b04f',
    messagingSenderId: '768002894558',
    projectId: 'tcu-tie',
    storageBucket: 'tcu-tie.appspot.com',
    iosClientId: '768002894558-cn6rn5lb3i035srdudgl1q2g1joret0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.takeiteasy',
  );
}
